# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: grpclb_backend_v1/backend.proto for package 'grpclb.backend.v1'

require 'grpc'
require 'grpclb_backend_v1/backend_pb'

module Grpclb
  module Backend
    module V1
      module LoadReport
        class Service

          include GRPC::GenericService

          self.marshal_class_method = :encode
          self.unmarshal_class_method = :decode
          self.service_name = 'grpclb.backend.v1.LoadReport'

          rpc :Load, LoadRequest, LoadResponse
        end

        Stub = Service.rpc_stub_class
      end
    end
  end
end
