# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpclb_backend_v1/backend.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='grpclb_backend_v1/backend.proto',
  package='grpclb.backend.v1',
  syntax='proto3',
  serialized_pb=_b('\n\x1fgrpclb_backend_v1/backend.proto\x12\x11grpclb.backend.v1\"\r\n\x0bLoadRequest\"\x1d\n\x0cLoadResponse\x12\r\n\x05score\x18\x01 \x01(\x03\x32U\n\nLoadReport\x12G\n\x04Load\x12\x1e.grpclb.backend.v1.LoadRequest\x1a\x1f.grpclb.backend.v1.LoadResponseb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_LOADREQUEST = _descriptor.Descriptor(
  name='LoadRequest',
  full_name='grpclb.backend.v1.LoadRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=67,
)


_LOADRESPONSE = _descriptor.Descriptor(
  name='LoadResponse',
  full_name='grpclb.backend.v1.LoadResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='score', full_name='grpclb.backend.v1.LoadResponse.score', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=98,
)

DESCRIPTOR.message_types_by_name['LoadRequest'] = _LOADREQUEST
DESCRIPTOR.message_types_by_name['LoadResponse'] = _LOADRESPONSE

LoadRequest = _reflection.GeneratedProtocolMessageType('LoadRequest', (_message.Message,), dict(
  DESCRIPTOR = _LOADREQUEST,
  __module__ = 'grpclb_backend_v1.backend_pb2'
  # @@protoc_insertion_point(class_scope:grpclb.backend.v1.LoadRequest)
  ))
_sym_db.RegisterMessage(LoadRequest)

LoadResponse = _reflection.GeneratedProtocolMessageType('LoadResponse', (_message.Message,), dict(
  DESCRIPTOR = _LOADRESPONSE,
  __module__ = 'grpclb_backend_v1.backend_pb2'
  # @@protoc_insertion_point(class_scope:grpclb.backend.v1.LoadResponse)
  ))
_sym_db.RegisterMessage(LoadResponse)


try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces


  class LoadReportStub(object):

    def __init__(self, channel):
      """Constructor.

      Args:
        channel: A grpc.Channel.
      """
      self.Load = channel.unary_unary(
          '/grpclb.backend.v1.LoadReport/Load',
          request_serializer=LoadRequest.SerializeToString,
          response_deserializer=LoadResponse.FromString,
          )


  class LoadReportServicer(object):

    def Load(self, request, context):
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')


  def add_LoadReportServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'Load': grpc.unary_unary_rpc_method_handler(
            servicer.Load,
            request_deserializer=LoadRequest.FromString,
            response_serializer=LoadResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'grpclb.backend.v1.LoadReport', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


  class BetaLoadReportServicer(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    def Load(self, request, context):
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


  class BetaLoadReportStub(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    def Load(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      raise NotImplementedError()
    Load.future = None


  def beta_create_LoadReport_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_deserializers = {
      ('grpclb.backend.v1.LoadReport', 'Load'): LoadRequest.FromString,
    }
    response_serializers = {
      ('grpclb.backend.v1.LoadReport', 'Load'): LoadResponse.SerializeToString,
    }
    method_implementations = {
      ('grpclb.backend.v1.LoadReport', 'Load'): face_utilities.unary_unary_inline(servicer.Load),
    }
    server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
    return beta_implementations.server(method_implementations, options=server_options)


  def beta_create_LoadReport_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_serializers = {
      ('grpclb.backend.v1.LoadReport', 'Load'): LoadRequest.SerializeToString,
    }
    response_deserializers = {
      ('grpclb.backend.v1.LoadReport', 'Load'): LoadResponse.FromString,
    }
    cardinalities = {
      'Load': cardinality.Cardinality.UNARY_UNARY,
    }
    stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
    return beta_implementations.dynamic_stub(channel, 'grpclb.backend.v1.LoadReport', cardinalities, options=stub_options)
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
