# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpclb_backend_v1/backend.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='grpclb_backend_v1/backend.proto',
  package='grpclb.backend.v1',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1fgrpclb_backend_v1/backend.proto\x12\x11grpclb.backend.v1\"\r\n\x0bLoadRequest\"\x1d\n\x0cLoadResponse\x12\r\n\x05score\x18\x01 \x01(\x03\x32U\n\nLoadReport\x12G\n\x04Load\x12\x1e.grpclb.backend.v1.LoadRequest\x1a\x1f.grpclb.backend.v1.LoadResponseb\x06proto3')
)




_LOADREQUEST = _descriptor.Descriptor(
  name='LoadRequest',
  full_name='grpclb.backend.v1.LoadRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=67,
)


_LOADRESPONSE = _descriptor.Descriptor(
  name='LoadResponse',
  full_name='grpclb.backend.v1.LoadResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='score', full_name='grpclb.backend.v1.LoadResponse.score', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=98,
)

DESCRIPTOR.message_types_by_name['LoadRequest'] = _LOADREQUEST
DESCRIPTOR.message_types_by_name['LoadResponse'] = _LOADRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LoadRequest = _reflection.GeneratedProtocolMessageType('LoadRequest', (_message.Message,), dict(
  DESCRIPTOR = _LOADREQUEST,
  __module__ = 'grpclb_backend_v1.backend_pb2'
  # @@protoc_insertion_point(class_scope:grpclb.backend.v1.LoadRequest)
  ))
_sym_db.RegisterMessage(LoadRequest)

LoadResponse = _reflection.GeneratedProtocolMessageType('LoadResponse', (_message.Message,), dict(
  DESCRIPTOR = _LOADRESPONSE,
  __module__ = 'grpclb_backend_v1.backend_pb2'
  # @@protoc_insertion_point(class_scope:grpclb.backend.v1.LoadResponse)
  ))
_sym_db.RegisterMessage(LoadResponse)



_LOADREPORT = _descriptor.ServiceDescriptor(
  name='LoadReport',
  full_name='grpclb.backend.v1.LoadReport',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=100,
  serialized_end=185,
  methods=[
  _descriptor.MethodDescriptor(
    name='Load',
    full_name='grpclb.backend.v1.LoadReport.Load',
    index=0,
    containing_service=None,
    input_type=_LOADREQUEST,
    output_type=_LOADRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_LOADREPORT)

DESCRIPTOR.services_by_name['LoadReport'] = _LOADREPORT

# @@protoc_insertion_point(module_scope)
