# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpclb_balancer_v1/balancer.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='grpclb_balancer_v1/balancer.proto',
  package='grpclb.balancer.v1',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n!grpclb_balancer_v1/balancer.proto\x12\x12grpclb.balancer.v1\"(\n\x06Server\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\x12\r\n\x05score\x18\x02 \x01(\x03\" \n\x0eServersRequest\x12\x0e\n\x06target\x18\x01 \x01(\t\">\n\x0fServersResponse\x12+\n\x07servers\x18\x01 \x03(\x0b\x32\x1a.grpclb.balancer.v1.Server2b\n\x0cLoadBalancer\x12R\n\x07Servers\x12\".grpclb.balancer.v1.ServersRequest\x1a#.grpclb.balancer.v1.ServersResponseb\x06proto3')
)




_SERVER = _descriptor.Descriptor(
  name='Server',
  full_name='grpclb.balancer.v1.Server',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='address', full_name='grpclb.balancer.v1.Server.address', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='score', full_name='grpclb.balancer.v1.Server.score', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=97,
)


_SERVERSREQUEST = _descriptor.Descriptor(
  name='ServersRequest',
  full_name='grpclb.balancer.v1.ServersRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='target', full_name='grpclb.balancer.v1.ServersRequest.target', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=99,
  serialized_end=131,
)


_SERVERSRESPONSE = _descriptor.Descriptor(
  name='ServersResponse',
  full_name='grpclb.balancer.v1.ServersResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='servers', full_name='grpclb.balancer.v1.ServersResponse.servers', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=133,
  serialized_end=195,
)

_SERVERSRESPONSE.fields_by_name['servers'].message_type = _SERVER
DESCRIPTOR.message_types_by_name['Server'] = _SERVER
DESCRIPTOR.message_types_by_name['ServersRequest'] = _SERVERSREQUEST
DESCRIPTOR.message_types_by_name['ServersResponse'] = _SERVERSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Server = _reflection.GeneratedProtocolMessageType('Server', (_message.Message,), dict(
  DESCRIPTOR = _SERVER,
  __module__ = 'grpclb_balancer_v1.balancer_pb2'
  # @@protoc_insertion_point(class_scope:grpclb.balancer.v1.Server)
  ))
_sym_db.RegisterMessage(Server)

ServersRequest = _reflection.GeneratedProtocolMessageType('ServersRequest', (_message.Message,), dict(
  DESCRIPTOR = _SERVERSREQUEST,
  __module__ = 'grpclb_balancer_v1.balancer_pb2'
  # @@protoc_insertion_point(class_scope:grpclb.balancer.v1.ServersRequest)
  ))
_sym_db.RegisterMessage(ServersRequest)

ServersResponse = _reflection.GeneratedProtocolMessageType('ServersResponse', (_message.Message,), dict(
  DESCRIPTOR = _SERVERSRESPONSE,
  __module__ = 'grpclb_balancer_v1.balancer_pb2'
  # @@protoc_insertion_point(class_scope:grpclb.balancer.v1.ServersResponse)
  ))
_sym_db.RegisterMessage(ServersResponse)



_LOADBALANCER = _descriptor.ServiceDescriptor(
  name='LoadBalancer',
  full_name='grpclb.balancer.v1.LoadBalancer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=197,
  serialized_end=295,
  methods=[
  _descriptor.MethodDescriptor(
    name='Servers',
    full_name='grpclb.balancer.v1.LoadBalancer.Servers',
    index=0,
    containing_service=None,
    input_type=_SERVERSREQUEST,
    output_type=_SERVERSRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_LOADBALANCER)

DESCRIPTOR.services_by_name['LoadBalancer'] = _LOADBALANCER

# @@protoc_insertion_point(module_scope)
