# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpclb_balancer_v1/balancer.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "grpclb.balancer.v1.Server" do
    optional :address, :string, 1
    optional :score, :int64, 2
  end
  add_message "grpclb.balancer.v1.ServersRequest" do
    optional :target, :string, 1
  end
  add_message "grpclb.balancer.v1.ServersResponse" do
    repeated :servers, :message, 1, "grpclb.balancer.v1.Server"
  end
end

module Grpclb
  module Balancer
    module V1
      Server = Google::Protobuf::DescriptorPool.generated_pool.lookup("grpclb.balancer.v1.Server").msgclass
      ServersRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("grpclb.balancer.v1.ServersRequest").msgclass
      ServersResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("grpclb.balancer.v1.ServersResponse").msgclass
    end
  end
end
